[package]
name = "RustyShell"
version = "0.1.1"
edition = "2024"

[[bin]]
name = "RustyShell_shellcode"
path = "src/shellcode.rs"
required-features = ["shellcode"]

[[bin]]
name = "RustyShell_shellcode_debug"
path = "src/shellcode.rs"
required-features = ["shellcode", "debug"]

[[bin]]
name = "RustyShell_debug_no_shellcode"
path = "src/debug-no-shellcode.rs"
required-features = ["debug"]

[dependencies]
widestring = { version = "1.2.1", default-features = false }

[features]
shellcode = []
debug = []