[package]
name = "HelLoader"
version = "0.1.1"
edition = "2024"

[[bin]]
name = "HelLoader_shellcode"
path = "src/shellcode.rs"
required-features = ["shellcode"]

[[bin]]
name = "HelLoader_shellcode_debug"
path = "src/shellcode.rs"
required-features = ["shellcode", "debug"]

[[bin]]
name = "HelLoader_debug_no_shellcode"
path = "src/debug-no-shellcode.rs"
required-features = ["debug"]

[dependencies]
wstr-literal = "0.1"

[features]
shellcode = []
debug = []