[env]
CODEGEN_ARGS = "-Z unstable-options -C panic=immediate-abort -C link-arg=-nostdlib -C link-arg=-Wl,-T./Linker.ld"
NIGHTLY_ARGS = "-Z build-std=std,core,panic_abort"
# FIX_FLAGS = "--config unstable.profile-rustflags=true --config profile.release.package.compiler_builtins.rustflags=['-Zshare-generics=off']"


[tasks.windows_gnu_shellcode]
description = "Cross compiling using gnu target"
script = [
    "cargo +nightly build --target x86_64-pc-windows-gnu --bin HelLoader_shellcode --features shellcode --release ${NIGHTLY_ARGS}"
]
env = { "RUSTFLAGS" = "${CODEGEN_ARGS}"}

[tasks.windows_gnu_debug_no_shellcode]
description = "Cross compiling using gnu target"
script = [
    "cargo +nightly build --target x86_64-pc-windows-gnu --bin HelLoader_debug_no_shellcode --release"
]