[env]
CODEGEN_ARGS = "-Z unstable-options -C panic=immediate-abort -C link-arg=-nostdlib -C link-arg=-Wl,-T./Linker.ld,-s -C codegen-units=256"
NIGHTLY_ARGS = "-Z build-std=std,core,panic_abort,compiler_builtins -Z build-std-features=compiler-builtins-mem"
# FIX_FLAGS = "--config unstable.profile-rustflags=true --config profile.release.package.compiler_builtins.rustflags=['-Zshare-generics=off']"


[tasks.windows_gnu_shellcode]
description = "Cross compiling using gnu target in shellcode"
script = [
    "cargo +nightly build --target x86_64-pc-windows-gnu --bin HelLoader_shellcode --features shellcode --release ${NIGHTLY_ARGS}",
    "objcopy -O binary --only-section=.text ./target/x86_64-pc-windows-gnu/release/HelLoader_shellcode.exe ./target/x86_64-pc-windows-gnu/release/HelLoader_shellcode.bin"
]
env = { "RUSTFLAGS" = "${CODEGEN_ARGS}"}

[tasks.windows_gnu_shellcode_debug]
description = "Cross compiling using gnu target in shellcode with debug"
script = [
    "cargo +nightly build --target x86_64-pc-windows-gnu --bin HelLoader_shellcode_debug --features shellcode,debug --release ${NIGHTLY_ARGS}",
    "objcopy -O binary --only-section=.text ./target/x86_64-pc-windows-gnu/release/HelLoader_shellcode_debug.exe ./target/x86_64-pc-windows-gnu/release/HelLoader_shellcode_debug.bin"
]
env = { "RUSTFLAGS" = "${CODEGEN_ARGS}"}

[tasks.windows_gnu_debug_no_shellcode]
description = "Cross compiling using gnu target not in shellcode with debug"
script = [
    "cargo +nightly build --target x86_64-pc-windows-gnu --bin HelLoader_debug_no_shellcode --features debug --release"
]