//! This module provide useful function.
//!
//! Functions and structures defined here are useful functions
//! that can be used throughout the code.

use alloc::vec::Vec;

/// Function to resolve printf function at runtime and use it for debug purposes in shellcode target
///
/// This function loads msvcrt thanks to LoadLibraryA and get the printf exported function from it
/// then calls it for debug purposes.
///
/// # Arguments
///
/// * `string` - A &str (literal string) or a String, that you can construct with the format! macro
#[cfg(feature = "debug")]
pub fn printf<T: Into<Vec<u8>>>(string: T) {
    use crate::runtime_resolve::{get_exported_symbol, get_module_address};
    use alloc::ffi::CString;
    use core::ffi::c_void;
    // Retrieving
    if let Ok(cstring) = CString::new(string) {
        if let Ok(kernel32_address) = get_module_address("kernel32.dll") {
            if let Ok(LoadLibraryA_address) = get_exported_symbol(kernel32_address, "LoadLibraryA")
            {
                let LoadLibraryA_func: extern "C" fn(*const u8) -> *const c_void =
                    unsafe { core::mem::transmute(LoadLibraryA_address) };
                let msvcrt_address = LoadLibraryA_func(c"msvcrt.dll".as_ptr().cast());

                if !msvcrt_address.is_null() {
                    if let Ok(printf_address) = get_exported_symbol(msvcrt_address, "printf") {
                        let printf_func: extern "C" fn(...) -> i32 =
                            unsafe { core::mem::transmute(printf_address) };
                        printf_func(cstring.as_ptr());
                        printf_func(c"\n".as_ptr());
                    }
                }
            }
        }
    }
}

/// Version of the printf function that does nothing. This is here to avoid compilation error when not compiling in debug mode
/// This actually comes with no overhead, because dead code elimination from the compiler will completely remove this
#[cfg(not(feature = "debug"))]
pub fn printf<T: Into<Vec<u8>>>(_string: T) {}

/// Macro to resolve a module and call a WINAPI inside that module without all the overhead of calling every function and checking every return value
///
/// # Arguments
///
/// * `module` - The string literal containing the module name to search for, omitting the suffix .dll
/// * `winapi` - The Winapi function to call, written with case like MSDN. This is necessary because it needs to match the function pointer type name that is generated by windows bindgen in winapi_bindings
/// * `result` - The variable into which you want the return value of the call
/// * `args`   - The arguments of the call to the WINAPI, just like you would have put them inside a direct call to this function
///
/// # Return value
///
/// The return value of the call is stored inside the variable passed as result argument
#[macro_export]
macro_rules! resolve_call_winapi {
    ($module:ident, $winapi:ident, $result:ident, $($args:tt)*) => {
        if let Ok(module_address) = get_module_address(core::concat!(core::stringify!($module), ".dll")) {
            if let Ok(winapi_address) = get_exported_symbol(module_address, core::stringify!($winapi)) {
                let winapi_func: winapi_bindings::$winapi = unsafe { core::mem::transmute(winapi_address) };
                $result = unsafe { winapi_func($($args)*) }
            } else {
                printf(format!("Couldn't resolve {} function", core::stringify!($winapi)));
            }
        } else {
            printf(format!("Couldn't resolve {} module", core::concat!(core::stringify!($module), ".dll")));
        }
    }
}

/// Macro to call a WINAPI without all the overhead of calling every function and checking every return value
///
/// # Arguments
///
/// * `module` - The variable containing the already resolved address of the module containing the WINAPI
/// * `winapi` - The Winapi function to call, written with case like MSDN. This is necessary because it needs to match the function pointer type name that is generated by windows bindgen in winapi_bindings
/// * `result` - The variable into which you want the return value of the call
/// * `args`   - The arguments of the call to the WINAPI, just like you would have put them inside a direct call to this function
///
/// # Return value
///
/// The return value of the call is stored inside the variable passed as result argument
#[macro_export]
macro_rules! call_winapi {
    ($module_address:ident, $winapi:ident, $result:ident, $($args:tt)*) => {
        if let Ok(winapi_address) = get_exported_symbol($module_address, core::stringify!($winapi)) {
            let winapi_func: winapi_bindings::$winapi = unsafe { core::mem::transmute(winapi_address) };
            $result = unsafe { winapi_func($($args)*) };
        } else {
            printf(format!("Couldn't resolve {} function", core::stringify!($winapi)));
        }
    };
}
