[package]
name = "rusty_shell"
version = "0.1.0"
edition = "2024"

[dependencies]
widestring = { version = "1.2.1", default-features = false }
windows-sys = { version = "0.61.2", default-features = false, features = [
    "Win32",
    "Win32_System",
    "Win32_System_SystemServices",
    "Win32_System_Diagnostics",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_SystemInformation",
    "Win32_System_Threading",
    "Win32_System_Kernel",
    "Win32_System_WindowsProgramming"
] }

# [build-dependencies]
# windows-bindgen = { version = "0.100" }

[features]
default = ["shellcode"]
shellcode = []
debug = []